# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Check code format

on:
  pull_request:
    branches: [ develop ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install linters
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-linters.txt 
    - name: Lint using built-in script
      run: bash shell/lint.sh
    - name: Precommit stage
      run: |
        source venv/bin/activate
        pip install pre-commit==3.3.3
        pre-commit install --install-hooks
        pre-commit run --all-files -c .pre-commit-config.yaml -v 
